---
name: Super Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Lint code with Super Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          RUN_LOCAL: true
        with:
          args: --languages python,yaml,javascript --disable all --enable python --enable yaml --enable javascript
